### PR TITLE
Add copy macro tab

### LINKED ISSUE #12: Add option to copy macro
Someone on curse had a great idea about adding an option to clone macro between toons.

https://www.curseforge.com/wow/addons/ema?comment=116

> One suggestion I have would be to add some ability to share or sync marcros with your alts. It's a big PITA to create the same macro multiple times. I've copied the global / character macro-cache.txt between accounts but that requires restarting the game. 

@ebonyfaye Do you want me to work on it ?

### PR DESCRIPTION
**Pull request by RobinFrcd**
- Copy macro from a character
- Edit it and send it to minions
- Delete all macros created with EMA

It's a start, maybe we want to add something else ?

Fix #12

### CODE REVIEW

**Comment by RobinFrcd** [comment]
Fixes #12

**Comment by ebonyfaye** [comment]
hi don't use a ( MinionsList ) jsut send to everyone if u have [~= ENA,charactername ] code then you don;t need need a   Minion/master system the "master" is not really for this sort of things now as there noneed and anyone can send from any toon then, then messing about changing master (all master should be doing is dealing with a few options if the player needs it (show only on one char) and mostly for talk to keep spam down.

**Comment by RobinFrcd** [comment]
Thanks for your feedback @ebonyfaye 

I've made requested changes + added a little doc for the user

**Comment by RobinFrcd** [comment]
@ebonyfaye I agree it's a bit less useful feature now, but I still think it's a nice to have one!

**Comment by RobinFrcd** [comment]
@ebonyfaye Will you continue to work on EMA in regard to recent ToS changes ?

**Comment by ebonyfaye** [comment]
i don't know atm am trying to still box

**Comment by ebonyfaye** [comment]
Ebony#9371 is my discord

**Pull request merged**
