### PR TITLE
Use Gossip namespace in Quest module

### LINKED ISSUE #21: Auto quest turn in doesn't work when multiple quests

### PR DESCRIPTION
**Pull request by RobinFrcd**
Fix #21

### CODE REVIEW

**Comment by RobinFrcd** [comment]
Fix #21

**Comment by ebonyfaye** [comment]
u still hsving problems with this?

my test it worked on every quest on every xpac i tried it on.

**Comment by RobinFrcd** [comment]
Yep, I still had the issue on wotlk argent tournament dailies :/

**Comment by ebonyfaye** [comment]
added by hand thanks for pointers

**Pull request closed without merging**
